# Generated by Django 5.2.8 on 2025-11-26 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('politique', 'Politique'), ('societe', 'Société'), ('enquete', 'Enquête & Reportage'), ('culture', 'Culture & Tradition du Nimba'), ('diaspora', 'Diaspora du Nimba'), ('economie', 'Économie Locale'), ('sport', 'Sport & Jeunesse')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_a_la_une', models.BooleanField(default=False, verbose_name='À la une')),
                ('vues', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='nimbaApp.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la publicité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='publicites/', verbose_name='Image')),
                ('lien', models.URLField(blank=True, verbose_name='Lien (URL)')),
                ('position', models.CharField(choices=[('header', 'Bannière en haut'), ('sidebar', 'Barre latérale'), ('footer', 'Bannière en bas'), ('article', 'Dans les articles')], default='sidebar', max_length=20, verbose_name='Position')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('nombre_clics', models.IntegerField(default=0, verbose_name='Nombre de clics')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-date_creation'],
            },
        ),
    ]
